# Global LLM configuration with multi-API key support
[llm]
model = "gemini-2.5-pro"
base_url = "https://generativelanguage.googleapis.com/v1beta/openai/"
api_key = "AIzaSyAwd6PcBM-07xBbbuBqBPc3svJsUMvyc1E"
max_tokens = 60000
temperature = 0.0

# Multi-API key configuration with rate limiting and automatic rotation

[[llm.api_keys]]
api_key = "AIzaSyAwd6PcBM-07xBbbuBqBPc3svJsUMvyc1E"
name = "1 Key"
max_requests_per_minute = 5
max_requests_per_hour = 100
max_requests_per_day = 100
priority = 1
enabled = true

[[llm.api_keys]]
api_key = "AIzaSyDwDj4i9tptBolcKGHMlqxMOi_CjisQdJE"
name = "2 Key"
max_requests_per_minute = 5
max_requests_per_hour = 100
max_requests_per_day = 100
priority = 2
enabled = true

[[llm.api_keys]]
api_key = "AIzaSyClSfseWKkublCjdZBIq-aYqPoB3jEWj28"
name = "3 Key"
max_requests_per_minute = 5
max_requests_per_hour = 100
max_requests_per_day = 100
priority = 3
enabled = true

[[llm.api_keys]]
api_key = "AIzaSyD_ElDcTSosqzd4Dy9L-4ygL3fP2zsWtq0"
name = "4 Key"
max_requests_per_minute = 5
max_requests_per_hour = 100
max_requests_per_day = 100
priority = 4
enabled = true

[[llm.api_keys]]
api_key = "AIzaSyAf__tW7KcUD1-uh9RzGg6Y5eS6e3_PNB0"
name = "5 Key"
max_requests_per_minute = 5
max_requests_per_hour = 100
max_requests_per_day = 100
priority = 5
enabled = true
